#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created 2021
@author: bragatte
# sections
## tips
### comments
"""

#Import img
from matplotlib import pyplot as plt
from skimage import io

img = io.imread("data/images/grasp/zikv/ALPVYLMTL_5K.jpg") #float conversplt.imshow(img) #matplotlib
### skimage
io.imshow(img) 
### matplot
plt.imshow(img)



from skimage.transform import rescale
##Always Rescale, Not resize
###gaussian smoothing can performed to avoid anti aliasing artifacts.
img_rescaled = rescale(img, 1.0 / 4.0, anti_aliasing=False)
###Check rescales image size in variable explorer

#A quick look at a few skimage functions
from skimage.filters import gaussian, sobel
### gaussian
gaussian_using_skimage = gaussian(img, sigma=1, mode='constant', cval=0.0)
plt.imshow(gaussian_using_skimage)

### sobel
img_gray = io.imread("data/images/grasp/zikv/ALPVYLMTL_5K.jpg", as_gray=True)
sobel_img = sobel(img_gray)  #Works only on 2D (gray) images
plt.imshow(sobel_img, cmap='gray')
